### ISSUE TITLE
[Feature] Allow to disable prefs saving

### ISSUE THREAD

**Issue by T8RIN** [pastthepixels/FreePaint#5]
I don't want to always save params when the app closes permanently, it would be good to add some switch of selecting that🐸

**Comment by pastthepixels** [comment]
Done!
<img width="200px" src="https://github.com/pastthepixels/FreePaint/assets/52388215/803e52ae-7bba-40c2-99fb-3d8e113f16de"/>

**Comment by T8RIN** [comment]
Good👀
